name: Pre-Release

on:
  push:
    branches:
      - development

jobs:
  pre-release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: | 
          npm clean-install
          npm ci
        
      - name: Semantic Release (Pre-Release)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          # Optionally, set a pre-release flag or version
          # for semantic-release to generate a pre-release.
          # For example, to specify a pre-release version:
          # NEXT_VERSION: preminor
        run: |
          # You may need to customize this command based on your semantic-release config.
          # Add any necessary flags or options to trigger a pre-release version.
          npx semantic-release
